hw1: homework1.o
	g++ homework1.o -o hw1
homework1.o: homework1.cc product_record.h
	g++ -c -g homework1.cc
part2: homework2.o
	g++ homework2.o -o part2
homework2.o: homework2.cc
	g++ -c -g homework2.cc
clean: 
	rm *.o
